### PR TITLE
a tiny patch for the width check

### LINKED ISSUE #1969: Support for arbitrary widths greater than 64
A feature of the [allo](https://github.com/cornell-zhang/allo) frontend is its use of arbitrarily precise types for all intermediate results. When the largest width is less than or equal to 64, Calyx is happy. However, evaluating a polynomial like `x * x * x * x * x` where `x` is 32b will cause a problem.

Here is a smaller toy program that has the issue:

```calyx
import "primitives/core.futil";

component main (@go go: 1) -> (@done done: 1, @stable output: 1) {
  cells {
    counter = std_reg(97);
    out_reg = std_reg(1);
    shift = std_lsh(97);
    out_slice = std_bit_slice(97, 41, 42, 1);
  }
  wires {
    
    static<1> group updateReg {
      shift.right = 97'b1;
      shift.left = counter.out;
      counter.in = shift.out;
      counter.write_en = 1'b1;
    }

    out_slice.in = counter.out;
    output = out_slice.out;

  }
  control {
    updateReg;
  }
}
```

```
$ calyx -b verilog ap.futil 
thread 'main' panicked at 'Widths greater than 64 are not supported.', calyx-ir/src/builder.rs:170:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by EclecticGriffin**
This should fix #1969, at least in the short term. There are still some limitations, so we cannot declare all arbitrary widths to be supported but this should at least unblock a few things.

### CODE REVIEW

File: calyx-ir/src/builder.rs [hunk 1]
```diff
@@ -163,12 +163,7 @@ impl<'a> Builder<'a> {
     pub fn add_constant(&mut self, val: u64, width: u64) -> RRC<ir::Cell> {
         // Ensure that the value can fit within the width
         assert!(
-            val < match width.cmp(&64) {
-                cmp::Ordering::Less => 1 << width,
-                cmp::Ordering::Equal => u64::MAX,
-                cmp::Ordering::Greater =>
-                    panic!("Widths greater than 64 are not supported."),
-            },
+            (64 - val.leading_zeros()) as u64 <= width,
```
Comment (rachitnigam) [inline calyx-ir/src/builder.rs:166]: Quick comment here about why this works?

**Review by rachitnigam — APPROVED** [review]
Minor change but otherwise LGTM!
