### PR TITLE
Remove `@externalized` attribute and update `@data` documentation

### LINKED ISSUE #2012: `@data` default assignment optimization does not work on external memories
Related to #2011 when external memories get externalized they lose their `@data` attributes on data ports which prevents them from having their default assignments optimized away in the verilog backend. This is particularly problematic because chaining with memory accesses can often be a frequency bottleneck for designs.

### PR DESCRIPTION
**Pull request by calebmkim**
Improves on #2019. 

Should close #2012.

### CODE REVIEW

File: calyx-backend/src/verilog.rs [hunk 1]
```diff
@@ -501,10 +502,7 @@ fn is_data_port(pr: &RRC<ir::Port>) -> bool {
         let cell = cr.borrow();
         // For cell.is_this() ports that were externalized, we already checked
         // that the parent cell had the `@data` attribute.
-        if cell.attributes.has(ir::BoolAttr::Data)
-            || (cell.is_this()
-                & port.attributes.has(ir::BoolAttr::Externalized))
-        {
+        if cell.attributes.has(ir::BoolAttr::Data) || (cell.is_this()) {
```
Comment (rachitnigam) [inline calyx-backend/src/verilog.rs:505]: Parens are not needed.

File: docs/lang/attributes.md [hunk 2]
```diff
@@ -199,18 +199,43 @@ When we have following two conditions:
...
 Since the value `'x` can be replaced with anything.
 
+`@data` can also appear on the output ports of a Calyx component.
+This represents when we want to optimize assignments to the port _within a Calyx component_.
+Consider the following example:
+```
+component main() ->(...@data out_write_data: 32....) {
+  ...
+  wires {
+    out_write_data = g ? out : 'x // we want to optimize to out_write_data = out
```
Comment (rachitnigam) [inline docs/lang/attributes.md:228]: This is great! Obviously, we don't support these "complete assignments" yet but it would be great to do that in the future so that we can represent the optimization within the compiler instead of inside the backend.

Comment (calebmkim) [reply docs/lang/attributes.md:233]: Ah yeah, that's a good point. I added a sentence in the docs clarifying that all these optimizations occur during the calyx->verilog translation, and that calyx doesn't support these types of complete assignments.

**Comment by rachitnigam** [comment]
LGTM!
